"""replace image_base64 text with image bytea

Revision ID: 0d95ecc4e285
Revises: 837fdd90d787
Create Date: 2026-05-22 08:48:27.848720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d95ecc4e285'
down_revision: Union[str, Sequence[str], None] = '837fdd90d787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('detections', 'image_base64')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('image_base64', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('detections', 'image')
    # ### end Alembic commands ###
