"""add image_base64 to detections

Revision ID: 38d0321bf307
Revises: a0a8d748f85d
Create Date: 2026-05-22 08:04:33.187094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d0321bf307'
down_revision: Union[str, Sequence[str], None] = 'a0a8d748f85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('image_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'image_base64')
    # ### end Alembic commands ###
