"""change camera_id to string

Revision ID: 837fdd90d787
Revises: 38d0321bf307
Create Date: 2026-05-22 08:42:28.464539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '837fdd90d787'
down_revision: Union[str, Sequence[str], None] = '38d0321bf307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'camera_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detections', 'camera_id',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
